src/Entity/Voiture.php
<?php

namespace App\Entity;

use App\Repository\VoitureRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VoitureRepository::class)]
class Voiture
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?float $prix_quotidien = null;

    #[ORM\Column]
    private ?float $prix_mensuel = null;

    #[ORM\Column]
    private ?int $places = null;

    #[ORM\Column]
    private ?bool $is_manuelle = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrixQuotidien(): ?float
    {
        return $this->prix_quotidien;
    }

    public function setPrixQuotidien(float $prix_quotidien): static
    {
        $this->prix_quotidien = $prix_quotidien;

        return $this;
    }

    public function getPrixMensuel(): ?float
    {
        return $this->prix_mensuel;
    }

    public function setPrixMensuel(float $prix_mensuel): static
    {
        $this->prix_mensuel = $prix_mensuel;

        return $this;
    }

    public function getPlaces(): ?int
    {
        return $this->places;
    }

    public function setPlaces(int $places): static
    {
        $this->places = $places;

        return $this;
    }

    public function isManuelle(): ?bool
    {
        return $this->is_manuelle;
    }

    public function setIsManuelle(bool $is_manuelle): static
    {
        $this->is_manuelle = $is_manuelle;

        return $this;
    }
}

src/Form/VoitureType.php
<?php

namespace App\Form;

use App\Entity\Voiture;
use Doctrine\ORM\Query\Expr\Select;
use Dom\Text;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class VoitureType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class, [
                    'label' => 'Nom du véhicule',
                ])
            ->add('description', TextareaType::class, [
                    'label' => 'Description',
                ])
            ->add('prix_quotidien', NumberType::class, [
                    'label' => 'Prix par jour (€)',
                    'scale' => 1,
                    'attr' => ['min' => 0],
                ])
            ->add('prix_mensuel', NumberType::class, [
                    'label' => 'Prix par mois (€)',
                    'scale' => 1,
                    'attr' => ['min' => 0],
                ])
            ->add('places', ChoiceType::class, [
                    'label' => 'Nombre de places',
                    'choices' => [
                            '1' => 1,
                            '2' => 2,
                            '3' => 3,
                            '4' => 4,
                            '5' => 5,
                            '6' => 6,
                            '7' => 7,
                            '8' => 8,
                            '9' => 9,
                        ],
                ])
            ->add('is_manuelle', ChoiceType::class, [
                    'label' => 'Boite de vitesse',
                    'choices' => [
                            'Manuelle' => true,
                            'Automatique' => false
                        ]

                ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Voiture::class,
        ]);
    }
}

src/Controller/AdminVoitureController.php
<?php

namespace App\Controller;

use App\Entity\Voiture;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;
use App\Form\VoitureType;
use Doctrine\ORM\EntityManagerInterface;
use Dom\Entity;

#[Route('/admin/voiture', name: 'app_admin_voiture_')]
final class AdminVoitureController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(): Response
    {
        return $this->render('admin_voiture/index.html.twig', [
            'controller_name' => 'AdminVoitureController',
        ]);
    }

    #[Route('/new', name: 'new')]
    public function new(Request $request, EntityManagerInterface $manager): Response
    {

        $voiture = new Voiture();
        $form = $this->createForm(VoitureType::class, $voiture);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $manager->persist($voiture);
            $manager->flush();
            return $this->redirectToRoute('app_index');
           
        }

        return $this->render('admin_voiture/new.html.twig', [
            'controller_name' => 'AdminVoitureController',
            'form' => $form,
        ]);
    }
}

src/Controller/IndexController.php
<?php

namespace App\Controller;

use App\Repository\VoitureRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class IndexController extends AbstractController
{
    #[Route('/', name: 'app_index')]
    public function index(VoitureRepository $repository): Response
    {

        $voitures = $repository->findAll();
        return $this->render('index/index.html.twig', [
            'controller_name' => 'IndexController',
            'voitures' => $voitures
        ]);
    }
}

src/Controller/VoitureController.php
<?php

namespace App\Controller;

use App\Entity\Voiture;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class VoitureController extends AbstractController
{
    #[Route('/voiture/{id}', name: 'app_voiture_show', requirements: ['id' => '\d+'])]
    public function show(int $id, EntityManagerInterface $em): Response
    {
        $voiture = $em->getRepository(Voiture::class)->find($id);

        if (!$voiture) {
            throw $this->createNotFoundException('Voiture non trouvée.');
        }

        return $this->render('voiture/show.html.twig', [
            'voiture' => $voiture,
        ]);
    }

        #[Route('/voiture/delete/{id}', name: 'app_voiture_delete', requirements: ['id' => '\d+'])]
    public function delete(int $id, EntityManagerInterface $em): Response
    {
        $voiture = $em->getRepository(Voiture::class)->find($id);

        if (!$voiture) {
            throw $this->createNotFoundException('Voiture non trouvée.');
        }

        $em->remove($voiture);
        $em->flush();

        return $this->redirectToRoute('app_index');
    }

}

templates/admin_voiture/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AdminVoitureController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>/Users/chirdon/Documents/OpenClassrooms/vehiloc/src/Controller/AdminVoitureController.php</code></li>
        <li>Your template at <code>/Users/chirdon/Documents/OpenClassrooms/vehiloc/templates/admin_voiture/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}

templates/admin_voiture/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Hello AdminVoitureController!
{% endblock %}

{% block body %}
<section id="add">
    <a href="index.html">← Retour</a>
    <h1>Ajouter une voiture</h1>
    {{ form_start(form) }}
        <div class="input">
           {{ form_row(form.nom) }}
        </div>
        <div class="input">
            {{ form_row(form.description) }}
        </div>
        <div class="flex-input">
            <div class="input">
                {{ form_row(form.prix_quotidien) }}
            </div>
            <div class="input">
            {{ form_row(form.prix_mensuel) }}
            </div>
        </div>
        <div class="flex-input">
            <div class="input">
                {{ form_row(form.places) }}
            </div>
            <div class="input">
                {{ form_row(form.is_manuelle) }}
            </div>
        </div>
        
        <button class="btn-add">Ajouter</button>
    {{ form_end(form) }}
</section>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">
        {% block stylesheets %}
        {% endblock %}

        {% block javascripts %}
            {% block importmap %}{{ importmap('app') }}{% endblock %}
        {% endblock %}
    </head>
    <body>

<header>
    <nav>
        <a href="index.html"><img src="{{ asset('img/logo.png') }}" alt="Vehicloc" /></a>
        <a href="add.html" class="btn-nav">Ajouter une voiture</a>
    </nav>
    <div class="flex-header">
        <div>
            <h1>Location de voitures à Saint-Étienne</h1>
            <p>Un service de location de voitures au mois pour répondre à vos besoins de mobilité.</p>
        </div>
        <div>
            <img src="{{ asset('img/car.png') }}" alt="Voiture">
        </div>
    </div>
</header>

        {% block body %}{% endblock %}

        <footer>
    <h2>Conduire avec nous</h2>
    <nav>
        <ul>
            <li><a href="#">Mentions légales</a></li>
            <li><a href="#">Nous contacter</a></li>
            <li>
                <a href="#"><img src="{{ asset('icons/instagram.png') }}" alt="Instagram" /></a>
                <a href="#"><img src="{{ asset('icons/facebook.png') }}" alt="Facebook" /></a>
            </li>
        </ul>
        <ul>
            <li><a href="#">Données personnelles</a></li>
            <li><a href="#">Questions fréquentes</a></li>
            <li class="copyright">© Véhicloc 2023</li>
        </ul>
    </nav>
</footer>
    </body>
</html>

templates/index/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Hello IndexController!
{% endblock %}

{% block body %}

    <section id="fleet">

        <h2>
            Découvrez la flotte de véhicules chez Véhicloc
        </h2>

        <p>
            Que vous ayez besoin d'une petite citadine agile, d'une berline élégante ou même d'un SUV spacieux, nous avons une variété de véhicules  pour répondre à vos exigences.
        </p>

        <div class="fleet-list">

            {% for voiture in voitures %}
                <article>
                    <div class="mini-car-title">
                        <a href="voiture/{{ voiture.id }}">
                            <h3>
                                {{ voiture.nom }}
                            </h3>
                            <p>
                                ou similaire | Saint-Étienne
                            </p>
                        </a>
                        <div>
                            <a href="/voiture/delete/{{ voiture.id }}">
                                <img src="{{ asset('icons/trash.png') }}" alt="Supprimer" />
                            </a>
                        </div>
                    </div>
                    <div class="mini-car-icons">
                        <div>
                            <img src="{{ asset('icons/persons.png') }}" alt="4 places" />
                            <p>
                                {{ voiture.places }}
                                places
                            </p>
                        </div>
                        <div>
                            <img src="{{ asset('icons/motor.png') }}" alt="Manuelle" />
                            <p>
                                {% if voiture.isManuelle %}
                                    Manuelle
                                {% else %}
                                    Automatique
                                {% endif %}
                            </p>
                        </div>
                        <div>
                            <img src="{{ asset('icons/km.png') }}" alt="km illimités" />
                            <p>
                                Km illimités
                            </p>
                        </div>
                        <div>
                            <img src="{{ asset('icons/plus.png') }}" alt="PLus" />
                            <p>
                                Plus
                            </p>
                        </div>
                    </div>
                    <div class="mini-car-price">
                        <p class="price-per-day">
                            {{ voiture.prixQuotidien }}
                            € / jour
                        </p>
                        <p class="price-per-month">
                            {{ voiture.prixMensuel }}
                            € / mois
                        </p>
                    </div>
                </article>

            {% endfor %}

        </div>
    </section>

    <section id="promises">
        <div>
            <h2>
                La promesse Véhicloc
            </h2>
            <div class="promise">
                <img src="{{ asset('icons/insurance.png') }}" alt="Assurance et Assistance" />
                <div class="promise-text">
                    <h3>
                        Assurance et Assistance
                    </h3>
                    <p>
                        Votre tranquillité d'esprit est notre priorité. Toutes nos locations mensuelles incluent une assurance complète et une assistance routière, pour garantir une conduite en toute sécurité.
                    </p>
                </div>
            </div>
            <div class="promise">
                <img src="{{ asset('icons/booking.png') }}" alt="Réservation facile" />
                <div class="promise-text">
                    <h3>
                        Réservation facile
                    </h3>
                    <p>
                        Notre plateforme vous permet de réserver votre voiture en quelques clics. Sélectionnez vos dates, choisissez le modèle qui vous convient et finalisez votre réservation en un rien de temps.
                    </p>
                </div>
            </div>
        </div>
        <div>
        </div>
    </section>

{% endblock %}

templates/voiture/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ voiture.nom }}
{% endblock %}

{% block body %}

    <section id="car">
        <a href="/">
            ← Retour
        </a>
        <h1>
            {{ voiture.nom }}
        </h1>

        <p class="description-car">
            {{ voiture.description }}
        </p>

        <div class="advantages">
            <div class="single-advantage">
                <img src="{{ asset('icons/checked.png') }}" alt="" />
                Km illimités
            </div>
            <div class="single-advantage">
                <img src="{{ asset('icons/checked.png') }}" alt="" />
                Taxe routière incluse
            </div>
            <div class="single-advantage">
                <img src="{{ asset('icons/checked.png') }}" alt="" />
                Assistance dépannage 24/7
            </div>
            <div class="single-advantage">
                <img src="{{ asset('icons/checked.png') }}" alt="" />
                Pas de frais caché
            </div>
            <div class="single-advantage">
                <img src="{{ asset('icons/checked.png') }}" alt="" />
                Assurance au tiers
            </div>
            <div class="single-advantage">
                <img src="{{ asset('icons/checked.png') }}" alt="" />
                Réservation sécurisée
            </div>
        </div>

        <hr>

            <p class="legal-information">
                Les conducteurs doivent avoir leur permis de conduire depuis au moins 5 ans.
            </p>

            <div class="total-rent">
                <span>
                    Total
                </span>
                <span>
                    {{ voiture.prixMensuel }}
                    €/mois
                </span>
            </div>
            <button class="btn-add">
                Louer pour
                {{ voiture.prixMensuel }}
                €/mois
            </button>
        <!-- Bouton inactif -->
        </section>

        <section id="insurances">
            <h2>
                Les Assurances et Assistances
            </h2>

            <div class="insurances-list">
                <div class="single-insurance">
                    <img src="{{ asset('icons/basic.png') }}" alt="Basique" />
                    <h3>
                        Protection Basique
                    </h3>
                    <p>
                        <img src="{{ asset('icons/checked.png') }}" alt="" />
                        Assurance dommages pour les dommages par collision, les rayures, les chocs et le vol.
                    </p>
                </div>
                <div class="single-insurance">
                    <img src="{{ asset('icons/complete.png') }}" alt="Complète" />
                    <h3>
                        Protection Complète
                    </h3>
                    <p>
                        <img src="{{ asset('icons/complete.png') }}" alt="" />
                        Assurance dommages pour les dommages par collision, les rayures, les chocs et le vol.
                    </p>
                    <p>
                        <img src="{{ asset('icons/complete.png') }}" alt="" />
                        Protection pneus et vitres.
                    </p>
                </div>
            </div>
        </section>
    {% endblock %}
    